### ISSUE TITLE
Update Account Balance

### ISSUE THREAD

**Issue by lkhalid0095** [makmn1/ttp-bankOfReact-assn9#3]
GIVEN I am on any page displaying the Account Balance
WHEN I view the Account Balance display area
THEN I should see an Account Balance that accurately represents my Debits subtracted from my Credits
AND I should be able to see a negative account balance if I have more Debits than Credits

**Comment by makmn1** [comment]
Account balance was made dynamic by having the App component hold the balance state and sharing it with child components Debit and Credit. As debits and credits were added, these child components would call a function in the App component (passing in a debit or credit amount) that updates the state accordingly.
